.TH GPSDRIVE 1 "" "Last modified: $Date$"
.SH NAME
gpsdrive \- displays GPS position on a map
.SH SYNOPSIS
.B gpsdrive [options]

.SH About this manual page

This manual page explains the basic functions of \fBGpsDrive\fR 2.10
and additional information regarding map setup and interfacing with
support software.

Within \fBGpsDrive\fR nearly all buttons have tooltips and there is also
a HELP window describing the usage of mouse buttons and keyboard shortcuts.

For additional information concerning advanced topics consult the
specialized README files, e.g. README.kismet, etc.


.SH DESCRIPTION

.B Gpsdrive 
is a car (bike, ship, plane, foot) navigation system.  It will
display your position on a map, record your track, and a number of
other handy functions.

\fBGpsDrive\fR connects to a GPS receiver and displays your position
on a zoomable map. The maps are auto-selected depending on your
position. You can choose the preferred map scale, which the
program then tries to match from the available maps. Basic worldwide
maps are provided and tools are included to help you add your own
localized maps.

.B GpsDrive
will work with the vast majority of GPS receivers which output NMEA
sentences to a serial device. This includes USB GPSs known
to the \fBGpsd\fR software, which handles the back-end communication
for \fBGpsDrive\fR. See the \fBGpsd\fR website
(\fIhttp://gpsd.berlios.de\fR) for an extensive list of GPS receivers
known to work with that software. In most cases your GPS will "just work".

"\fBGpsd\fR is a service daemon that monitors one or more GPSes attached
to a host computer through serial or USB ports, making all data on the
location/course/velocity of the sensors available to be queried on
a TCP port of the host computer. With \fBgpsd\fR, multiple GPS client
applications (such as navigational and wardriving software) can share
access to GPSes without contention or loss of data."

You must install and launch \fBgpsd\fR before running \fBGpsDrive\fR.


.SH DISCLAIMER
.B Do not use GpsDrive as a primary means of navigation!

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License (GPL) for more details.


.SH OPTIONS

.TP
.B \-?, --help
Displays a short help message.
.TP
.B \-e, --embedded
Don't show the GUI; for use in external GTK apps.
.TP
.B \-f, --force-position
Force display of position even if the GPS fix is invalid. Before a GPS has a
fix it often reports its position as 0,0. And if it has lost a fix some makes
of GPS will repeat the last known position together with a fix-is-bad indicator.
Normally (without this flag) \fBGpsDrive\fR skips plotting these points.
Useful for debugging.
.TP
.B \-i, --ignore-checksum
Ignore NMEA checksum. (risky, only for broken GPS receivers)
.TP
.B \-p, --position-mode
Start in Position Mode. This will let you explore around your maps
independently of your GPS position (or lack thereof).
.TP
.B \-s, --nosplash
Don't show the startup splash screen.
.TP
.B \-t, --touchscreen
Set this special mode if you only have a single mouse button, for example
when using \fBGpsDrive\fR on a touchscreen display.
.TP
.B \-v, --verbose
Displays some basic debug information to the terminal as the program runs.
.TP
.B \-x, --use-DBUS
Use DBUS for communication with \fBgpsd\fR; this disables socket communication.
.TP
.B \-A, --alt-offset=\fI<OFFSET>\fR
Adjust the displayed altitude by adding this value.
.TP
.B \-B, --gpsd-server=\fI<SERVER>\fR
Server name of the NMEA server. You can connect your GPS receiver to a
remote \fIhost\fR which is running \fBgpsd\fR and display the position
on your local machine.
.TP
.B \-C, --config-file=\fI<FILE>\fR
Set this if you wish to use an alternative configuration file.
.TP
.B \-D, --debug=\fI<LEVEL>\fR
Set the debugging level. A level of 0 will show no debug information,
while a level of 100 will show \fBa lot\fR of debugging information.
If you have problems or program crashes, set this high enough to display
relevant information send this output to the authors.
See also the \fBBUGS\fR section below.
.TP
.B \-F, --friends-server=\fI<SERVERFILE>\fR
Select a friends server to exchange position information with other
people, e.g. \fIfriendsd.gpsdrive.de\fR.
You can also set this from the Preferences/Friends menu.
You can start your own friends server with the included \fBfriendsd\fR program.
More details are in the \fBFRIENDSD\fR section below.
.TP
.B \-G, --geometry=\fI<GEOMETRY>\fR
Specify the window geometry, e.g. 800x600.
.TP
.B \-M, --gui-mode=\fR[\fIcar\fR|\fIpda\fR|\fIdesktop\fR]
Set GUI mode. The default layout is '\fIdesktop\fR'. \fICar\fR modes sets
up the display in a fullscreen mode suitable for use with a small LCD
touchscreen. \fIPDA\fR mode dedicates even more screen real-estate to
the map, controls are hidden behind tabs.
.TP
.B \-N, --nmeaout=\fI<FILE>\fR
Set a serial device, PTY master, or file to send NMEA sentences to.
This is useful if you use \fBGpsDrive\fR in simulation mode to provide
other GPS applications with test data.
.TP
.B \-S, --screenshot=\fI<PATH>\fR
Take auto-screenshots of different GUI windows then exit. Image files will
be saved to the secified \fIpath\fR. Don't touch gpsdrive while this is
running!
.TP
.B \-T, --run-test
Run some internal unit tests and then exit.
.TP
.B \--version
Shows the program version together with the SVN revision of the main
gpsdrive.c source. If you send a bug report, also include this output.
.TP
.B \--display=\fI<DISPLAY>\fR
The X-Window display to use.


.SH CONNECTING A GPS RECEIVER

.B Start GPSD
.br
This program runs as daemon in background and provides a server
which sends the GPS data on port number 2947. You can download and
learn more about \fBgpsd\fR at \fIhttp://gpsd.berlios.de\fR.

Once \fBgpsd\fR is running you can monitor the raw NMEA output of your GPS
with \fBtelnet localhost 2947\fR and after the connection is made hit the 
\fBR\fR key to see the NMEA sentences. You can use the \fBxgps\fR
program that comes with \fBgpsd\fR for a more comprehensive test.


.SH USAGE

Start GpsDrive as normal user with:
.B gpsdrive
from your shell, if you want another language see section 
.I LOCALISATION

On some distributions you may find a "\fBGpsDrive\fR" entry in your
Gnome or KDE menu.

It is important that you have installed GpsDrive as root, so it can
find the necessary files. 
.B Don't start GpsDrive as root!

You can use GpsDrive without a GPS device connected. If you do so,
GpsDrive will automatically start in
.B Simulator mode 
if no working GPS receiver is connected and no gpsd
is running. This mode is shown by a rotating globe.

In simulator mode the pointer can move on the map (if enabled in settings
menu). You can also stop gpsd if it is already running with the "Stop GPSD" Button.

If you have connected a GPS-Receiver, you see in the 
.I GPS Info
window how many satellites are in view. You can click on this image to switch to the 
.I Satellite position view.
.br
You must have at least 3 satellites in view. If you want to see your
altitude, you need at least 4 satellites.  The antenna of your GPS
receiver must have free sight to the sky, so you cannot use it
indoors. More satellites gives you a better accuracy.

If your receiver has not enough satellites with usable signal, the
GPS Info window is red. If your signal is ok and gives a valid
position, the GPS Info window is green.

There are 3 modes in which GpsDrive is operating:

.B Normal mode:

This mode is entered if you have a GPS receiver connected. The cursor is at
the position your receiver sends.

Black and a red arrows show your position on the map. The 
.B black arrow
is pointing to your selected target, the 
.B red arrow
shows the direction in which you are moving.
.br
If you have no valid position the arrows are blinking.

.B Simulation

If GpsDrive finds no GPS-receiver at program start, it
shows the last position and the cursor will move to the targets you
set. You can set your target by right-mouse click on the map or by
selecting a waypoint from the FIND menu.

.B Position mode

This mode is activated by clicking on the "Pos. mode" button or if you
"Jump" to a target in the FIND menu.

In this mode, you can temporarily change the position for looking around and
jumping to other positions (i.e. for downloading maps). In this mode this
is 
.B not your real position
and is marked as an rectangle.

You can set the position by a simple left-mouse click on the map.

You can leave the position mode by by clicking on the "Pos. mode"
button or middle-mouse click or right-mouse click (which also sets
your target).


.SH OPENSTREETMAP MAPS
GpsDrive now supports OSM maps with the help of the Mapnik renderer.
To activate this mode you have to choose the mapnik option.


.SH MAP DOWNLOAD

You can easily download maps from the internet with the
.B Download
button. GpsDrive stores an index of your maps in the file
map_koord.txt in your ~/.gpsdrive/maps/ directory. You can use
another directory for your maps if you like, to change this set
the appropriate directory in the Preferences menu.

.SH About maps

There is a file called "map_koord.txt" in your ~/.gpsdrive/maps/
directory. Here is a sample:

top_WORLD.jpg 0.00000 0.00000 88226037
.br
map_file0000.gif 53.60751 10.01145 3160000
.br
map_file0001.gif 43.08210 12.24552 3160000
.br
map_file0002.gif 49.81574 9.71454 7900000
.br
map_file0003.gif 47.72837 14.46487 592500
.br


The first column is the filename, then comes the latitude, the longitude
and the scale of the map. Typical scales for all of Europe might be
1:10,000,000, and 1:100,000 for a town. To see detailed streets in a city,
choose a scale like 1:10,000 or 1:5,000.

You can figure out the exact "scale" factor by meters/pixel * 2817.947378.
The 2817 number may be some ancient screen dpi converted to pixels/meter?
Who knows. But that's what it is and it works.

GpsDrive selects the map with the best scale for your position. So get
a map e.g. for Europe, Austria, and Vienna if you want to drive in
Vienna.

There is also the program
.IR gpsfetchmap.pl
provided to download multiple maps for a bigger area.
.br
.B Please consider the copyright information and terms of service
at \fIwww.expedia.com\fR if you want to use their maps!
.br
.B Do not misuse this service by downloading more maps as you need! 
You will risk being blocked by these servers, and possibly cause
trouble for the gpsdrive project.

File formats:

The decimal points in way.txt must always be a dot ('.'), in
map_koord.txt '.' or ',' are possible. If you download maps from
within the program, GpsDrive writes the map_koord.txt respecting your
LC_NUMERIC setting.


.SH Can I use other maps?

You can also use your own (self drawn, scanned, exported from GIS, ...) maps.
The maps must be in PNG, JPEG, GIF, TIFF, or another common file format
(the format must be recognized by the gdk-pixbuf library).
The lat/long coordinates you write into the "map_koord.txt" file is measured
at the center of the map. The map must have a size of 1280x1024 pixels! 

Important! The maps must be named "map_*" for UTM-like projections
(lat:lon = 1:cos(lat)) and "top_*" for lat/lon Plate carrée projection
(lat:lon = 1:1). The prefix is given so that gpsdrive knows how to
scale the maps correctly. Alternatively the maps can be stored without
prefix in subdirectories of $HOME/.gpsdrive/maps/ which end in "_map" or
"_top". The georeferencing information (center coordinate and scale factor)
for the maps in those subdirectories must be recorded in the main
"map_koord.txt" file, typically stored in the \fI~/.gpsdrive/maps/\fR
directory.

Beware if you are using an image originating from a map projection with a
significant deviation between true north and the map projection's local
+y direction (known as the Convergence Angle). \fBGpsDrive\fR assumes that
true north is always directly up! i.e. the Central Meridian of the map
projection is located at the map tile's center. For some map projections
and areas of the country this can be a really bad assumption and your map
will be significantly rotated. This effect is most visible at map scales
covering a large area. This does not affect lat/lon maps.

There is an "import assistant" built in. Use it to import your unreferenced
maps.


.SH Importing waypoints:

The manual way:

You may create a file "way.txt" in your ~/.gpsdrive directory
which looks like:

DFN-Cert                53.577694    9.991263 FRITZ
.br
Finkenwerder            53.541765    9.842541 AIRPORT
.br
Fritz_Wohnung           53.582700    9.971390 FRITZ

The rows are: label latitude longitude waypoint-type. You may omit the
waypoint type.

There is no need to create the way.txt file yourself, you can add the
waypoints with GpsDrive using the "x" key. See help menu.



.SH Route planning
There is no route planning feature at the moment. Route planning would
need the use of commercial maps and a database license which costs
more than EUR 10.000. 

.SH PROXY SERVER
If you must access the internet via a proxy server, you have to set the
environment variable
.B HTTP_PROXY
or
.B http_proxy
to a value like
.I http://proxy.provider.com:3128
where 3128 in this example is the proxy port.

.SH MOUSE CONTROL
You can switch on the
.B Position mode
by selecting this option in the menu.

If you switched to "position mode" a rectangle is the
cursor and no position is shown. If you zoom or select another map
scale with the slider, this is done for the position of the
rectangle-cursor in the same manner as it would be your actual
position. If you click with the left button near the border, GpsDrive will
scroll the map or load the next map if you are on the margin of the map.

The middle mouse button or the "Pos. mode" menu entry switches back to
normal mode. The same happens if you select a target with the right
mouse button.  Shift-left-mouse-button and shift-right-mouse-button
or using the mouse wheel changes the map scale.

Please have also a look into the
.B Help
menu in GpsDrive to be informed about the actual mouse functions and key
shortcuts.

.SH Add new waypoints
You can simply add new waypoints in two ways:

o To add a waypoint at the
.B current (GPS) position, 
simply press CTRL and RIGHT-mouse-click. You can also press the
.B x
key.

o To add a waypoint at the
.B mouse position,
simply press CTRL and LEFT-mouse-click. You can also press the
.B y
key.

In the popup window add the waypoint name (spaces will be converted to
underscores) and choose a waypoint type (see below for predefined
waypoint types).
 
.SH Icons for waypoints
At the moment there a three different icon themes available, but not
everone has distinct icons for every type. Currently you can choose the
themes only by editing the entry "icon_theme" in the config file
"~/.gpsdrive/gpsdriverc". The possible themes are:
"square.big", "square.small" and "classic".

.SH SQL support

For managing a larger number of waypoints you should use SQL
support. This needs to install a SQL server on your machine. At the
moment, only MySQL is supported.

Don't be afraid, MySQL doesn't need much resources, is very fast, and makes the
management (including selection of waypoint types) of the waypoints
much easier. In SQL mode you can select the waypoints to display in the
.B setup
menu.

GpsDrive use MySQL automatically if it finds the shared library 
.I libmysqlclient.so.10 
and the MySQL Server is running and a connection to the database is possible.
For first use you have to run
.B geoinfo.pl --create-db --fill-defaults
once.

.B Please read README.SQL for information how to setup the SQL database.



.SH Routes
A route is a list of waypoints. GpsDrive guides you from one waypoint
to the next on the route. 
You can add waypoints to a route using
the waypoint (select target) window. You can also add comments to a
waypoint which will be spoken by the speech system and also be shown
in the map window as scrolling text.

.SH Comments for routes
To add comments create a file with the same name as the waypoint file,
but change the suffix to .dsc, i.e way-trip.txt and way-trip.dsc, then
enter the comments in the way*.dsc file in the kind of:

$waypointname
Text which is displayed and spoken

$nextwaypointname
another text

Example:

$Fritz_Wohnung
Hier wohnt Fritz, der Autor von diesem Programm. Er freut sich auf Besuch und eine
Einladung zu einem saftigen Steak.
                                                                                
$Hubertus
Hier wohnt Hubertus, ein Freund von Fritz.

There is no limit of the length of the comment. Important is to start
the line with '$name' and the comment in the next lines.

.SH KISMET support
Gpsdrive supports
.IR kismet.
Kismet is a 802.11b wireless network (WLAN) sniffer. If you have
kismet running, gpsdrive will detect it and program starts and shows
new WLAN access points in real time on the map. SQL mode is necessary to
use Gpsdrive with Kismet. WLAN accesspoints which are already
stored in the SQL database from prior wardrivings are ignored. If you
have voice output in gpsdrive, you hear information about the newly
found accesspoint.

Please see also the file
.IR README.kismet

.SH LOCALISATION

If you have installed the program it will display messages in english,
german, french, italian, dutch, dansk, hungarian, slovak, swedish, turkish or
spanish if your language is set either with LANG or LANGUAGE. LANGUAGE
overrides all other settings. Call "locale" to see the settings and
call "set" if LANG or LANGUAGE is set. For german do:

.B export LANGUAGE=de

and then call gpsdrive in this shell.

You can also start it with the line 
.B LANGUAGE=de gpsdrive
without setting the language for the shell.

Sometimes you have to do use LANG instead of LANGUAGE.

If your own language isn't available, please contact me if you want to
make the translations.

.SH SPEECH OUTPUT

If you want speech output you have to install the festival speech output
system.
See 
.I http://fife.speech.cs.cmu.edu/festival
for information.

For german output you have to get the german festival from
.I www.ims.uni-stuttgart.de/phonetik/synthesis/index.html

If you have a functional festival software call it as server with:

festival --server

When you start GpsDrive it will detect the server on port 1314 and
puts out some status information as speech. You also have an
additional button (Mute) to switch off sound output.

GpsDrive tries to select the correct language for your locale.
The -l option can force the languages for speech
output. At the moment english, spanish, and german are supported. GpsDrive
sets festival into the proper language. If the initialisation is not
correct, have a look into 
.I gpsdrive.c
and edit following defines do your needs:

#define FESTIVAL_ENGLISH_INIT "(voice_ked_diphone)"

#define FESTIVAL_GERMAN_INIT "(voice_german_de3_os)"

#define FESTIVAL_SPANISH_INIT "(voice_el_diphone)"

For this, you need the voices ked_diphone for english, german_de3_os
for german (this is a MBROLA voice) and el_diphone for spanish.

There is now an unsupported build of festival including english, german
and spanish support.
.B Download 
it from GpsDrive homepage 
.B mirrors
and extract
the tar file in the directory /usr/local as root:

.br 
cd /usr/local
.br
tar -xvzf festivalbuild.tar.gz

Start the server with
.B /usr/local/festival/bin/festival --server


.SH FRIENDSD server

There is a server program, called
.B friendsd
which acts as server for the position of your friends. If you enable
it in the settings menu, 
then you can see the position of all gpsdrive connected with this
server. 

You will see the position of your friends as a car symbol on the map,
including the name, time, day of week and the speed of his last connection.
The blue arrow shows the last reported direction of your friend.

The time is transmitted as UTC, but shown on the display as your local time, 
so it is also correct if your friend lives in another time zone.

The server uses port 50123 (UDP), so be sure that you open the port in
your firewall. The server needs no root privileges and should run as
normal user or a special user with no privileges. The server was NOT
tested for security.

There is a friends server running on friends.gpsdrive.de, you can try it
if you enable it in the settings menu.

You can also send messages to other mobile targets (Misc. Menu/Messages)


.SH MAILING LIST

The primary means of support and coordination of program development
happens on the \fBGpsDrive\fR mailing list.

Information about subscription and a searchable archive can be found
at \fIhttp://www.gpsdrive.de/support.shtml\fR.


.SH BUGS
Please send bug reports to the development team! If we don't know about
them we can't fix them and then the remain unfixed. 

File bug reports in our tracker at \fIhttp://bugzilla.gpsdrive.de/\fR.
You will need to create yourself a SourceForge account at that site,
it is rather painless and only takes a minute. This ensures you get
feedback about the bug and we can communicate with you if we need
further information.

Please report the version (\fBgpsdrive --version\fR), screen size, platform,
and as much specific information about how to reproduce the bug as possible.
Whenever possible cut and paste exact error messages and take screenshots.
It is helpful to run gpsdrive for a minute with the -D debug level option
set high and send us the output.

If \fBgpsdrive\fR crashes with a SegFault, we will need a backtrace of the
program as well. Assuming \fBGpsDrive\fR was built with debugging symbols and
the binaries were not stripped of them, create a backtrace by running the
\fBGpsDrive\fR the GNU debugging software as follows:

  \fBgdb `which gpsdrive`\fR

Inside the debugger do:

  \fBrun\fR (if you use command line arguments place these after the word \fBrun\fR)

When you get the SegFault type in:

  \fBbt full\fR

and send us this output. This gives us an indication of exactly what the program
was doing when it broke.


.SH AUTHORS
\fBGpsDrive\fR was originally written by Fritz Ganter. Today it is maintained
and improved by a worldwide team of volunteer developers centered around the
\fIhttp://www.gpsdrive.de\fR website. The source code repository, bug tracker,
and collaborative wiki help site are hosted at \fIhttp://gpsdrive.sourceforge.net\fR.
A partial list of contributing authors can be found in the Help->About menu within
the program.


.SH WARRANTY
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.


.SH COPYRIGHT
Copyright (c) 2001-2004 by Fritz Ganter
.br
Copyright (c) 2005-2008 by the members of the GpsDrive Development Team
.br

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version. Indeed, you are encouraged to do so!
