option(WITH_SCRIPTS "Install perl scripts and modules" ON)
option(WITH_MAPNIK "Build with mapnik support" ON)
option(WITH_GDA3 "Build with GDA3 database support" ON)
option(WITH_GDAL "Build with experimental GDAL support" OFF)
option(WITH_SPEECH "Build with support of speech output" ON)
