option(WITH_SCRIPTS "Install perl scripts and modules" ON)
option(WITH_MAPNIK "Build with mapnik support" ON)
option(WITH_POSTGIS "Build with PostGIS database support" ON)
option(WITH_GDAL "Build with experimental GDAL support" OFF)
option(WITH_SPEECH "Build with support of speech output" ON)
option(WITH_DBUS "Build with DBUS support" OFF)
option(WITH_BASEMAPS "Build with Basemaps pictures" ON)
option(MAEMO "Build gpsdrive for maemo/hildon platform" OFF)
option(WITH_FRIENDSD "Build friendsd" ON)
option(WITH_KISMET "Build with kismet support" ON)
option(DEBUG "Build with debug -D support" ON)
option(WITH_NAVIGATION "Build with routing support" OFF)

