option(WITH_SCRIPTS "Install perl scripts and modules" ON)
option(WITH_MAPNIK "Build with mapnik support" ON)
option(WITH_GDA3 "Build with GDA3 database support" ON)
option(WITH_GDAL "Build with experimental GDAL support" OFF)
option(WITH_SPEECH "Build with support of speech output" ON)
option(WITH_DBUS "Build with DBUS support" OFF)
option(MAEMO "Build gpsdrive for maemo/hildon platform" OFF)
option(WITH_FRIENDSD "Build with friendd support" ON)
option(WITH_KISMET "Build with kismet support" ON)
option(DEBUG "Build with debug -D support" ON)
option(WITH_NAVIGATE "Build with routing support" ON)

