#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_input medium gpsdrive/initdb || true
db_go

if false ; then
db_get gpsdrive/initdb
INIT_DB=$RET

if [ "x$INIT_DB" = "xtrue" ] ; then
        echo "asking for gpsdrive Options import"
        db_input medium gpsdrive/importosm
	db_go

	db_get gpsdrive/importosm
	IMPORT_OSM=$RET
	if [ "x$IMPORT_OSM" = "xtrue" ] ; then
	    db_input medium gpsdrive/importosmarea
	    db_go
	fi
fi
fi
